import { Bebas_Neue } from '@next/font/google';
import Header from "../components/Header";
import Footer from "../components/Footer";
import "../style/globals.css";

const bebasNeue = Bebas_Neue({
  weight: '400', // ou '700', dependendo do peso que você deseja
  subsets: ['latin'],
});

export const metadata = {
  title: "ValorantCard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
        <body className={bebasNeue.className} >
          <Header/>
          {children}
          <Footer/>
        </body>
    </html>
  );
}
